exec-once=push-to-talk -k BTN_EXTRA -n MOUSE9 /dev/input/by-id/usb-SteelSeries_SteelSeries_Rival_650_Wireless_000000000000-if01-event-mouse


# bind = , mouse:276, pass, class:^(discord)$  # Pass MOUSE5 to TeamSpeak3.


monitor = HDMI-A-1, 1920x1080@60, 0x0, 1
monitor = DP-1, 2560x1440@180, 1920x0, 1

xwayland { force_zero_scaling = true }


plugin {
    split-monitor-workspaces {
        # count = 10
        # keep_focused = 0
        # enable_notifications = 0
        # enable_persistent_workspaces = 0

        # set this to 1 for gnome-like workspace switching
        # link_monitors = 0

        # if you want a different monitor order

        # you can also set max workspaces per monitor
        max_workspaces = HDMI-A-1, 5
    }
}

exec-once = xrandr --output DP-1 --primary
