windowrule {
  name = windowrule-1
  float = on
  match:title = ^(Console window for .+ Prism Launcher .+)
}

windowrule {
   name = open files
   float = on
   match:title = ^(Open Files)
   match:class = ^(org.gnome.Nautilus)
}

windowrule {
  name = windowrule-2
  fullscreen = on
  match:class = ^(Loading...)$ # war thunder
}

windowrule {
  name = windowrule-3
  fullscreen = on
  match:title = ^(Wuthering Waves)$ # Wuthering waves
}


windowrule {
  name = windowrule-4
  workspace = special:special2 silent
  match:class = ^(discord)
}

windowrule {
  name = windowrule-5
  workspace = 91 silent
  match:title = ^(Steam)
}

#windowrulev2 = immediate, class:^(steam_app_1017180)$
