{ ... }:
{
  imports = [
    ./hyprland
    ./shells
    ./ranger
    ./terminals
    ./discord
    ./firefox
    ./tofi
    ./editors
    ./waybar
    ./atuin
    ./krita.nix
    ./prism-launcher.nix
    ./wlogout.nix
    ./vlc.nix
    ./game_launchers
    ./obsidian.nix
    ./wine.nix
    ./mpv
    ./notification-daemon
    ./qbittorrent.nix
    ./bottles.nix
    ./hyfetch
    ./wallpaper
    ./browsers
    ./file-managers
    ./hyprlock.nix
    ./nixcord.nix
  ];
}
